version: '3.7'
services:
  php:
    volumes:
      - './apps/symfony-blog/:/usr/src/app'
      - './docker/php/config.json:/.composer/config.json'

  nginx:
    volumes:
      - './apps/symfony-blog/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'

  adminer:
    ports:
      - '${ADMINER_PORT}:8080'

